# FARA OCR Processing System - Requirements
# Install with: pip install -r requirements.txt

# Core dependencies
opencv-python>=4.8.0
pytesseract>=0.3.10
pdf2image>=3.1.0
PyMuPDF>=1.23.0
pandas>=2.0.0
numpy>=1.24.0

# AWS dependencies (for Textract - recommended)
boto3>=1.28.0
botocore>=1.31.0

# Configuration and utilities
PyYAML>=6.0
pathlib2>=2.3.7; python_version<'3.4'

# Data processing
Pillow>=10.0.0
scikit-image>=0.21.0

# Optional: for enhanced text processing
python-dateutil>=2.8.2
regex>=2023.6.3

# Optional: for parallel processing
joblib>=1.3.0

# Development and testing (optional)
pytest>=7.4.0
pytest-cov>=4.1.0
